{% set name = "GPyOpt" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e714daa035bb529a6db23c53665a762a4ab3456b9329c19ad3b03983f94c9b2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - gpy >=1.8
    - numpy >=1.7
    - python
    - scipy >=0.16

test:
  imports:
    - GPyOpt
    - GPyOpt.acquisitions
    - GPyOpt.core
    - GPyOpt.core.evaluators
    - GPyOpt.core.task
    - GPyOpt.experiment_design
    - GPyOpt.interface
    - GPyOpt.methods
    - GPyOpt.models
    - GPyOpt.objective_examples
    - GPyOpt.optimization
    - GPyOpt.plotting
    - GPyOpt.util

about:
  home: http://sheffieldml.github.io/GPyOpt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Bayesian Optimization Toolbox
  dev_url: https://github.com/SheffieldML/GPyOpt

extra:
  recipe-maintainers:
    - xhochy
