bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: v5TS1hI0IF2263kvg69omAYAhx63Efoqd4zbSzysMXBrdpKz8ILoNre28K9unQ5snBPuBjtjntWJSLBZrVqpAAc+ZjiG/6n59Jzp8hzEyNTu0JpoiKdN+v8MJVMcqDhP7xy3G9ci4KSsRBItG+GgedLiGPqri4yUVzQlyE05vdVRV6DI8qmMFef/qk8UQisjPysuZyIZqplTxIephO+EOyoIdXDvdCv2nC63sTlsQLsrl4w/bMWBcgSciuodt5EdDGQ/wZbbjvMaFp53Sq43+ipKAyZzHm0ooxqYhNAfAbLjcWsGXUZ3K9Gb1uS7n8T6mBDZM6cx9SUvUOP/LTbMTki+GQEInWkFZzovSZKr77p2/JV9NS5/MlCQPg/x9H2v+288aflW/8W13nu5FdzvxhNz/laO8ghCi/7J8b/DnbFjnLco2q/Vf4MiaHqOZQ7pxdYB8XFi3bz457nPwxSyp1zRy9cInnH2Q/y5qfX4dmtrVrkZij7IFBhnOCIZEmDpXszpQ8vs1/3rv2qtoYRP10zoKEpkyEYT0aGKx7CbnAGWwuy0eb0s0EKqe3rMmQpdozz4IULH4jSCex3wYnT2+GzY8InkT4h1H5959uKUcy8yggE7MfN6RWNFKQrLj1UdHOok925LBhwy/DqHxJ0kAuSKid2uprCUe/se88zhJ+I=
conda_forge_output_validation: true
